name: hello

# Evento
on:
  push:
  

# Trabajos
jobs:
  trabajo1:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Echo Terminal
        run: echo Hello, world!
        
      - name: Di la fecha de hoy
        run: date
